spring:
  profiles:
    active: local #basic configuration select


#springboot logback configuration settings
---
spring:
  profiles: local
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%clr(%-10p)][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework: INFO
---
spring:
  profiles: dev
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: ./logs/tmsLog.log
    max-history: 30
  level:
    org:
    springframework: INFO
  logback:
    rollingpolicy:
      file-name-pattern: "/logs/abc.%d{yyyy-MM-dd}.%i"


#local environment
---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://webservice.ce5zdjsnjhyy.ap-northeast-2.rds.amazonaws.com:3306/teametastorage
    username: admin
    password: admin1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
---
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    boot:
        admin:
            client:
                url: http://ec2-3-36-84-108.ap-northeast-2.compute.amazonaws.com:8000/
                username: admin
                password: admin
                instance:
                    metadata:
                        user:
                            name: admin
                            password: admin
                    service-url: http://teametastorage.com