server:
  port: 8010
spring:
  profiles:
    active: local #basic configuration select


#springboot logback configuration settings
---
spring:
    config:
      activate:
        on-profile: local
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%clr(%-10p)][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework: INFO
---
spring:
    config:
      activate:
        on-profile: dev
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line]-%msg%n"
  file:
    name: ./logs/tmsLog.log
    max-history: 30
  level:
    org:
    springframework: INFO
  logback:
    rollingpolicy:
      file-name-pattern: "/logs/abc.%d{yyyy-MM-dd}.%i"
---
logging:
  file:
    name: "/var/log/sample-boot-spplication.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
#local environment
---
spring:
  datasource:
#    url: jdbc:mariadb://192.168.11.21:3306/teametastorage
    url: jdbc:mariadb:// 180.70.85.99:8050/teametastorage
    username: admin
    password: admin1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update